# Generated by Django 5.2.5 on 2025-08-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('en_attente', 'En attente de confirmation'), ('confirmee', 'Confirmée'), ('expediee', 'Expédiée'), ('terminee', 'Terminée'), ('annulee', 'Annulée (Stock réintégré)'), ('annulee_client', 'Annulée par le client')], default='en_attente', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('adresse_livraison', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_facture', models.CharField(blank=True, max_length=100, unique=True)),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('prix_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
