# Generated by Django 5.2.5 on 2025-08-28 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
        ('facture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='operateur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'vente']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_gerees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facture.commande'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facture.commande'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.produit'),
        ),
    ]
