# Generated by Django 5.2.5 on 2025-08-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, help_text='Laisser vide pour une création automatique.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='slug',
            field=models.SlugField(blank=True, help_text='Laisser vide pour une création automatique.', max_length=120, unique=True),
        ),
    ]
